// Copyright The prometheus-operator Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	v1alpha1 "github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1alpha1"
	monitoringv1alpha1 "github.com/prometheus-operator/prometheus-operator/pkg/client/applyconfiguration/monitoring/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeRemoteWrites implements RemoteWriteInterface
type FakeRemoteWrites struct {
	Fake *FakeMonitoringV1alpha1
	ns   string
}

var remotewritesResource = v1alpha1.SchemeGroupVersion.WithResource("remotewrites")

var remotewritesKind = v1alpha1.SchemeGroupVersion.WithKind("RemoteWrite")

// Get takes name of the remoteWrite, and returns the corresponding remoteWrite object, and an error if there is any.
func (c *FakeRemoteWrites) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.RemoteWrite, err error) {
	emptyResult := &v1alpha1.RemoteWrite{}
	obj, err := c.Fake.
		Invokes(testing.NewGetActionWithOptions(remotewritesResource, c.ns, name, options), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.RemoteWrite), err
}

// List takes label and field selectors, and returns the list of RemoteWrites that match those selectors.
func (c *FakeRemoteWrites) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.RemoteWriteList, err error) {
	emptyResult := &v1alpha1.RemoteWriteList{}
	obj, err := c.Fake.
		Invokes(testing.NewListActionWithOptions(remotewritesResource, remotewritesKind, c.ns, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.RemoteWriteList{ListMeta: obj.(*v1alpha1.RemoteWriteList).ListMeta}
	for _, item := range obj.(*v1alpha1.RemoteWriteList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested remoteWrites.
func (c *FakeRemoteWrites) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchActionWithOptions(remotewritesResource, c.ns, opts))

}

// Create takes the representation of a remoteWrite and creates it.  Returns the server's representation of the remoteWrite, and an error, if there is any.
func (c *FakeRemoteWrites) Create(ctx context.Context, remoteWrite *v1alpha1.RemoteWrite, opts v1.CreateOptions) (result *v1alpha1.RemoteWrite, err error) {
	emptyResult := &v1alpha1.RemoteWrite{}
	obj, err := c.Fake.
		Invokes(testing.NewCreateActionWithOptions(remotewritesResource, c.ns, remoteWrite, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.RemoteWrite), err
}

// Update takes the representation of a remoteWrite and updates it. Returns the server's representation of the remoteWrite, and an error, if there is any.
func (c *FakeRemoteWrites) Update(ctx context.Context, remoteWrite *v1alpha1.RemoteWrite, opts v1.UpdateOptions) (result *v1alpha1.RemoteWrite, err error) {
	emptyResult := &v1alpha1.RemoteWrite{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateActionWithOptions(remotewritesResource, c.ns, remoteWrite, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.RemoteWrite), err
}

// Delete takes name of the remoteWrite and deletes it. Returns an error if one occurs.
func (c *FakeRemoteWrites) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(remotewritesResource, c.ns, name, opts), &v1alpha1.RemoteWrite{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeRemoteWrites) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionActionWithOptions(remotewritesResource, c.ns, opts, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.RemoteWriteList{})
	return err
}

// Patch applies the patch and returns the patched remoteWrite.
func (c *FakeRemoteWrites) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.RemoteWrite, err error) {
	emptyResult := &v1alpha1.RemoteWrite{}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithOptions(remotewritesResource, c.ns, name, pt, data, opts, subresources...), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.RemoteWrite), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied remoteWrite.
func (c *FakeRemoteWrites) Apply(ctx context.Context, remoteWrite *monitoringv1alpha1.RemoteWriteApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.RemoteWrite, err error) {
	if remoteWrite == nil {
		return nil, fmt.Errorf("remoteWrite provided to Apply must not be nil")
	}
	data, err := json.Marshal(remoteWrite)
	if err != nil {
		return nil, err
	}
	name := remoteWrite.Name
	if name == nil {
		return nil, fmt.Errorf("remoteWrite.Name must be provided to Apply")
	}
	emptyResult := &v1alpha1.RemoteWrite{}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithOptions(remotewritesResource, c.ns, *name, types.ApplyPatchType, data, opts.ToPatchOptions()), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.RemoteWrite), err
}
